### ISSUE TITLE
Is there a docker-compose.yml file?

### ISSUE THREAD

**Issue by drustanyjt** [ngxingyu/ros-devcontainer#1]
I think the file no longer exists in the repo (but it's in the structure in the README)

**Comment by ngxingyu** [comment]
The readme structure is slightly outdated, you can refer to the other docker-compose files e.g. `docker-compose-vrx.yml` for a sample setup, all the `docker-compose` files simply launches the different images and mounts different volumes, and you can modify it as needed. I usually launch the containers using one of the tmuxinator configs (e.g. vrx-sim.yml launches `docker-compose-vrx.yml`. Will add some documentation for this in our wiki soon.
